[package]
name = "ui-compiler"
version = "0.1.0"
authors = ["Jáchym Toušek <enumag@gmail.com>"]
edition = "2021"

[dependencies]
Inflector = "*"
log = "0.4.20"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
simplelog = "0.12.1"
