cargo run onikakushi steam win
cargo run onikakushi steam unix
cargo run watanagashi steam win
cargo run watanagashi steam unix
cargo run tatarigoroshi steam win
cargo run tatarigoroshi steam unix
cargo run tatarigoroshi mg win
cargo run tatarigoroshi mg unix
cargo run himatsubushi steam win
cargo run himatsubushi steam unix
cargo run meakashi steam win
cargo run meakashi steam unix
cargo run meakashi gog win
cargo run tsumihoroboshi steam win
cargo run tsumihoroboshi steam unix
