name: Build ui-compiler.exe and optionally Build Assets

on:
 push:
   tags:
     - '*'

jobs:
  windows_build:
    name: Windows Build
    runs-on: windows-latest
    steps:
      # Download the repository
      - uses: actions/checkout@v2

      # Caching for Rust
      - name: Cache rust builds
        uses: Swatinem/rust-cache@v2

      - name: Build ui-compiler.exe
        run: cargo build

      - name: Download and install dependencies, then build assets
        run: python build.py github_actions

      # Publish a release (tagged commits)
      # For more info on options see: https://github.com/softprops/action-gh-release
      - name: Release (tag)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') # only publish tagged commits
        with:
          files: |
            output/*.7z
            target/debug/ui-compiler.exe
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
